### PR TITLE
adding sbpunited logo

### PR DESCRIPTION
**Pull request by GlazovYuri**

### CODE REVIEW

**Comment by GlazovYuri** [comment]
> You have to adapt https://github.com/RoboCup-SSL/ssl-status-board/blob/master/frontend/src/teamLogoUrl.js as well.

Thanks, I forgot about that. I'll fix it now

**Comment by GlazovYuri** [comment]
Well, I think I don't know git very well. I'll make a new Pull Request now to keep the original branch clean.

**Comment by g3force** [comment]
A tipp for the future: Don't use the master branch in your fork. I usually merge with rebase, so you kind of mess up your forks master branch. Better create a feature branch in your fork.

**Comment by GlazovYuri** [comment]
Thank you, I'll keep that in mind :)

**Pull request closed without merging**
